apiVersion: v1
kind: ConfigMap

metadata:
  name: gateway-config

data:
  application.properties: |
    spring.application.name=apigateway

    server.port=8100

    app.version=1.0.0

    security.jwt.key.private=${SECRET_KEY_PRIVATE_DEV}

    spring.cloud.gateway.routes[0].id=auth-service
    spring.cloud.gateway.routes[0].uri=http://auth-service:8101
    spring.cloud.gateway.routes[0].predicates[0]=Path=/api-auth-service/**
    spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
    spring.cloud.gateway.routes[1].id=dinamica-service
    spring.cloud.gateway.routes[1].uri=http://dinamica-service:8102
    spring.cloud.gateway.routes[1].predicates[0]=Path=/api-dinamica-service/**
    spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
    logging.level.org.springframework.security=TRACE
    logging.level.org.springframework.web=DEBUG
    logging.level.org.springframework.cloud.gateway=DEBUG