spring.application.name=${NAME_DEV_API_GATEWAY}

server.port=${PORT_DEV_API_GATEWAY}
security.jwt.key.private=${SECRET_KEY_PRIVATE_DEV}

eureka.client.enabled=true
eureka.client.service-url.defaultZone=${SERVER_PRODUCCION}:${PORT_DEV_EUREKA_SERVER}/eureka/

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true