spring.application.name=apigategay

server.port=8100
security.jwt.key.private=miclaveprivada123456789

app.version=@project.version@

eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8762/eureka/

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true