name: CI - Dev

on:
  push:
    branches:
      - dev

jobs:
  build-dev:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      # Cache Gradle
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build JAR
        run: |
          chmod +x gradlew
          APP_VERSION=dev-${GITHUB_SHA:0:7} ./gradlew clean bootJar

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build imag (DEV)
        run: docker build --build-arg APP_VERSION=dev-${GITHUB_SHA:0:7} -t ${{ secrets.DOCKERHUB_USERNAME }}/microservices:apigateway-dev .

      - name: Push image (DEV)
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/microservices:apigateway-dev