name: Publish Docker image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with gradle inside Docker
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          gradle:8.10.2-jdk21-alpine \
            ./gradlew bootJar

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/microservices:apigateway-image .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/microservices:apigateway-image